<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="5" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="8601" started-at="2018-06-04T11:09:33Z" finished-at="2018-06-04T11:09:42Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="8601" started-at="2018-06-04T11:09:33Z" finished-at="2018-06-04T11:09:42Z">
      <class name="com.test.suit.discover.InfoSummary">
        <test-method status="PASS" signature="setInfo()[pri:0, instance:com.test.suit.discover.InfoSummary@7ea9e1e2]" name="setInfo" is-config="true" duration-ms="8563" started-at="2018-06-04T11:09:33Z" finished-at="2018-06-04T11:09:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setInfo -->
        <test-method status="PASS" signature="noareaCount()[pri:0, instance:com.test.suit.discover.InfoSummary@7ea9e1e2]" name="noareaCount" duration-ms="8" started-at="2018-06-04T11:09:41Z" finished-at="2018-06-04T11:09:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- noareaCount -->
        <test-method status="FAIL" signature="rbalarm_Count()[pri:0, instance:com.test.suit.discover.InfoSummary@7ea9e1e2]" name="rbalarm_Count" duration-ms="2" started-at="2018-06-04T11:09:41Z" finished-at="2018-06-04T11:09:41Z">
          <exception class="junit.framework.ComparisonFailure">
            <message>
              <![CDATA[expected:<...96> but was:<...00>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.ComparisonFailure: expected:<...96> but was:<...00>
at junit.framework.Assert.assertEquals(Assert.java:81)
at junit.framework.Assert.assertEquals(Assert.java:87)
at com.test.suit.discover.InfoSummary.rbalarm_Count(InfoSummary.java:73)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.ComparisonFailure -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- rbalarm_Count -->
        <test-method status="PASS" signature="rbmeterCount()[pri:0, instance:com.test.suit.discover.InfoSummary@7ea9e1e2]" name="rbmeterCount" duration-ms="1" started-at="2018-06-04T11:09:41Z" finished-at="2018-06-04T11:09:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- rbmeterCount -->
        <test-method status="FAIL" signature="rmalarm_Count()[pri:0, instance:com.test.suit.discover.InfoSummary@7ea9e1e2]" name="rmalarm_Count" duration-ms="3" started-at="2018-06-04T11:09:41Z" finished-at="2018-06-04T11:09:42Z">
          <exception class="junit.framework.ComparisonFailure">
            <message>
              <![CDATA[expected:<...904> but was:<...896>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.ComparisonFailure: expected:<...904> but was:<...896>
at junit.framework.Assert.assertEquals(Assert.java:81)
at junit.framework.Assert.assertEquals(Assert.java:87)
at com.test.suit.discover.InfoSummary.rmalarm_Count(InfoSummary.java:67)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.ComparisonFailure -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- rmalarm_Count -->
        <test-method status="PASS" signature="rmmeterCount()[pri:0, instance:com.test.suit.discover.InfoSummary@7ea9e1e2]" name="rmmeterCount" duration-ms="1" started-at="2018-06-04T11:09:42Z" finished-at="2018-06-04T11:09:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- rmmeterCount -->
      </class> <!-- com.test.suit.discover.InfoSummary -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
