<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="7" hostname="JINWX-PC" name="com.test.suit.discover.InfoSummaryTests" tests="8" failures="1" timestamp="12 六月 2018 07:17:17 GMT" time="0.006" errors="0">
  <testcase name="dmaAllHPCheck" time="0.006" classname="com.test.suit.discover.InfoSummaryTests">
    <failure type="java.lang.AssertionError" message="expected [1002] but found [1016]">
      <![CDATA[java.lang.AssertionError: expected [1002] but found [1016]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:442)
at com.test.suit.discover.InfoSummaryTests.dmaAllHPCheck(InfoSummaryTests.java:92)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- dmaAllHPCheck -->
  <testcase name="rbmeterCount" classname="com.test.suit.discover.InfoSummaryTests">
    <skipped/>
  </testcase> <!-- rbmeterCount -->
  <testcase name="dmaAllHeaders" classname="com.test.suit.discover.InfoSummaryTests">
    <skipped/>
  </testcase> <!-- dmaAllHeaders -->
  <testcase name="noareaCount" classname="com.test.suit.discover.InfoSummaryTests">
    <skipped/>
  </testcase> <!-- noareaCount -->
  <testcase name="rmmeterCount" classname="com.test.suit.discover.InfoSummaryTests">
    <skipped/>
  </testcase> <!-- rmmeterCount -->
  <testcase name="rbalarm_Count" classname="com.test.suit.discover.InfoSummaryTests">
    <skipped/>
  </testcase> <!-- rbalarm_Count -->
  <testcase name="rmalarm_Count" classname="com.test.suit.discover.InfoSummaryTests">
    <skipped/>
  </testcase> <!-- rmalarm_Count -->
  <testcase name="dmaAllHP_SITE_Check" classname="com.test.suit.discover.InfoSummaryTests">
    <skipped/>
  </testcase> <!-- dmaAllHP_SITE_Check -->
</testsuite> <!-- com.test.suit.discover.InfoSummaryTests -->
